version : '3.4'
services:
  mysql:
    build: 
      context: germes-admin
      dockerfile: src/main/resources/docker/mysql.dockerfile
    logging:
      driver: none
    networks:
      - network1
    environment:    
      - MYSQL_USER=germes
      - MYSQL_PASSWORD=germes
      - MYSQL_DATABASE=germes  
    env_file:
      - mysql.env 
  admin:
    build: 
      context: .
      dockerfile: germes-presentation/src/main/resources/docker/tomcat-maven.dockerfile
      args:
        - war_path=/opt/admin.war
    ports:
      - "9000:8080"
    networks:
      - network1
    depends_on:
      - mysql
    entrypoint: bash -c "sleep 5s && catalina.sh run"
    environment:
      - JAVA_OPTS=--add-modules java.xml.bind
  client:
    build: 
      context: .
      dockerfile: germes-presentation/src/main/resources/docker/tomcat-maven.dockerfile
      args:
        - war_path=/opt/client.war      
    ports:
      - "8080:8080"
    networks:
      - network1
    depends_on:
      - mysql
    entrypoint: bash -c "sleep 5s && catalina.sh run"
    environment:
      - JAVA_OPTS=--add-modules java.xml.bind                              
networks:
  network1:
    driver: bridge
  